slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Nav2-friendly frame convention
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # LaserScan topic published by ydlidar_ros2_driver_node
    scan_topic: /scan

    # slam_toolbox publishes map->odom
    transform_publish_period: 0.02
    map_update_interval: 0.5
    tf_buffer_duration: 30.0
    transform_timeout: 10.0
    
    # Increase the tolerance for slightly older or delayed LiDAR scan messages 
    # to account for network latency between Jetson TF and RPi LiDAR
    max_tollerance: 2.0

    # Mapping basics
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.2

    # IMPORTANT:
    # A queue size of 1 will almost always overflow the tf2 message filter and
    # cause: "Message Filter dropping message ... because the queue is full".
    scan_queue_size: 50
    restamp_tf: true